[package]
name = "starforge-render"
version = "0.1.0"
edition = "2024"

[dependencies]
# Local dependencies
starforge-core = { path = "../starforge-core" }

# Inherited dependencies from the workspace
smithay = { workspace = true }
wgpu = "0.20.1"
thiserror = { workspace = true }