[package]
name = "starforge-core"
version = "0.1.0"
edition = "2024"

[dependencies]
# Inherited dependencies from the workspace
smithay = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }